# 服务端口配置
server:
  port: 8080
  #端口号
  servlet:
    context-path: /api   #项目根路径（前面必须加/）

spring:
  #项目名称
  application:
    name: smart-house
  # Mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autoroom?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=true&serverTimezone=Asia/Shanghai
    username: root
    password: hq963497073
  # 系统文件上传大小限制
  servlet:
    multipart:
      max-file-size: 20MB #单文件最大20MB
      max-request-size: 20MB #单次请求最大20MB

# Mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #指定Mybatis的Mapper文件
  type-aliases-package: com.example.springboottemplate.entity  #指定Mybatis的实体目录
  #开启驼峰命名 处理下划线映射到实体
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted #逻辑删除字段名
      logic-delete-value: 1 #已删除
      logic-not-delete-value: 0 #未删除

# 分页查询配置
pagehelper:
  helper-dialect: mysql  # 数据库方言
  reasonable: true       # 分页合理化，pageNum<=0时会查询第一页，pageNum>pages时会查询最后一页
  support-methods-arguments: true # 支持通过Mapper接口参数来传递分页参数

# 登录令牌配置
jwt:
  secret-key: "y7a9fLp9Xy2A/sB1nOq6r4tJwYz8Cv0EeKcHj3mNl+Q="  # Base64编码的256位密钥
  access-token-expire: 3600000     #1小时 访问令牌过期时间（毫秒）
  refresh-token-expire: 604800000   #7天 刷新令牌过期时间（毫秒）

# 文件上传（关于文件大小限制在上面的spring-servlet-multipart中）
upload:
  dir: ${user.home}/xy_uploads/ #文件上传存储路径
#  dir: C:/用户/96349/xy_uploads/  # 末尾必须加斜杠
  public-path: /upload-images/** #对外暴露的url路径